apiVersion: 1

contactPoints:
  - orgId: 1
    name: incident-responder-webhook
    receivers:
      - uid: responder-hook
        type: webhook
        settings:
          url: http://host.docker.internal:8001/alerts
          httpMethod: POST

policies:
  - orgId: 1
    receiver: incident-responder-webhook
    group_by: ["alertname", "fonte"]
    group_wait: 5s
    group_interval: 15s
    repeat_interval: 1h
